### ISSUE TITLE
Installed Greengenes2 and redbiom in Qiime2 but getting a connection error 

### ISSUE THREAD

**Issue by waalkes** [biocore/redbiom#129]
I am trying to get Greengenes2 and redbiom working in Qiime2.  I am using this tutorial:

https://forum.qiime2.org/t/querying-for-public-microbiome-data-in-qiita-using-redbiom/4653

but when I try the first command: redbiom summarize contexts

I get the error below.  I see that at times there have been server issues.  Any help getting me going?

Thanks,

Adam
+++++++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3e92eee160>: Failed to establish a new connection: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='qiita.ucsd.edu', port=7329): Max retries exceeded with url: /HGETALL/state:contexts.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e92eee160>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/bin/redbiom", line 8, in <module>
    sys.exit(cli())
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/redbiom/commands/summarize.py", line 16, in summarize_caches
    contexts = redbiom.summarize.contexts()
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/redbiom/summarize.py", line 29, in contexts
    contexts = get('state', 'HGETALL', 'contexts')
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/redbiom/_requests.py", line 95, in f
    return _parse_validate_request(s.get(url), cmd)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/home/waalkes/miniconda3/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='qiita.ucsd.edu', port=7329): Max retries exceeded with url: /HGETALL/state:contexts.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e92eee160>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by wasade** [comment]
Hi @waalkes, thanks for reaching out! This would happen your system is unable to connect with `qiita.ucsd.edu` on port 7329. It can happen sporadically. I cannot recreate it right now, and don't have an indication of services being down. Would it be possible to retry the `redbiom summarize contexts` call?

**Comment by waalkes** [comment]
Thanks for the quick response.  I can ping the site just fine but I still get the error.  Let me check with our guys about the port or if there is anything that might be an issue on our side.

**Comment by waalkes** [comment]
It was a firewall issue.  Opened the port and it is working.  Thanks!

**Comment by wasade** [comment]
Wonderful, glad to hear!!
