### ISSUE TITLE
redbiom search metadata NUMBER should fail gracefully

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/redbiom#44]
Currently the following exception is shown on screen:

```
Traceback (most recent call last):
  File "/Users/yoshikivazquezbaeza/miniconda/envs/devbiom/bin/redbiom", line 11, in <module>
    load_entry_point('redbiom', 'console_scripts', 'redbiom')()
  File "/Users/yoshikivazquezbaeza/miniconda/envs/devbiom/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/devbiom/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/devbiom/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yoshikivazquezbaeza/miniconda/envs/devbiom/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yoshikivazquezbaeza/miniconda/envs/devbiom/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/devbiom/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/yoshikivazquezbaeza/git_sw/redbiom/redbiom/commands/search.py", line 87, in search_metadata
    for i in redbiom.search.metadata_full(query, categories):
  File "/Users/yoshikivazquezbaeza/git_sw/redbiom/redbiom/search.py", line 51, in metadata_full
    stemmer=stem_f))
  File "/Users/yoshikivazquezbaeza/git_sw/redbiom/redbiom/set_expr.py", line 91, in seteval
    raise TypeError("Unsupported node type: %s" % ast.dump(node))
TypeError: Unsupported node type: Num(n=111)
```

**Comment by wasade** [comment]
That is graceful from the developer perspective... but yes, agree that it would be useful to be more clear to the user

**Comment by ryanc16** [comment]
I think your point is that this information is useful from a developers perspective, but to an user (especially a non-technical one), this information is confusing and quite intimidating. Perhaps a good solution would be to introduce some exception handling into the application and inform the user with human consumable error messages. In addition, a log can be created when a command encounters fails, and the location of that log can be shown to the user for details of the error. The contents of that log can be requested in future issues to help developers debug and fix the issue.
